---
server:
  vars:
    k3s_version: v1.32.5+k3s1
    api_endpoint: k3s-master
    kubeconfig: ~/.kube/homelab-config
  hosts:
    k3s-master:

agent:
  hosts: {}

k3s_cluster:
  children:
    server:
    agent: