- name: Create argo-events namespace
  kubernetes.core.k8s:
    name: argo-events
    api_version: v1
    kind: Namespace
    state: present

- name: Install Argo events
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install-validating-webhook.yaml
    namespace: argo-events
